### ISSUE TITLE
IGR deffine problem

### ISSUE THREAD

**Issue by WarlockSVG** [Team-Resurgent/CerbiosTool#1]
The IGR full and IGR Shutdown value box are not separately definable.

I can only select the "IGR full value box" by pressing the "TAB" key until the "IGR full value box" is selected.
The "IGR Shutdown value box" is also selected when the "IGR Full value box" is selected. They have the same IGR value.
Selecting one of them with the mouse doesn't work on those two value boxes.

![2023-06-02 - 12-04-34](https://github.com/Team-Resurgent/CerbiosTool/assets/33853101/d7beacf7-8986-4026-991b-5bc19871894c)

**Comment by WarlockSVG** [comment]
By saving the configuration to file, then changing the value for "IGRFull" or "IGRShutdown" in the configuration file, then loading the edited configuration file allows one to have the IGR fully set to the desired key combos.

So this workaround will do for now ;-)

**Comment by EqUiNoX-Labs** [comment]
@WarlockSVG think is fixed in latest builds, please confirm

**Comment by HoRnEyDvL** [comment]
Closed due to no response. Issue should be fixed if it still an issue then please raise new ticket.

Thanks
