### ISSUE TITLE
Logo falsly blacked out

### ISSUE THREAD

**Issue by Gunnar-GO** [Team-Resurgent/CerbiosTool#6]
i set a green theme at the tool, in 2.2 / 2.3 it worked flawless. in 2.4.1 with the [Cerbios Tool V2.0.1](https://github.com/Team-Resurgent/CerbiosTool/releases/tag/V2.0.1) Pre-release it renders completely to black, thankfull it starts without hasitation , so my TSOP-modification is not going to hell.

**Comment by antoxa2584x** [comment]
Same here

**Comment by HoRnEyDvL** [comment]
Should be fixed in latest Cerbios release :)
